### PR TITLE
Version 2.01

### PR DESCRIPTION
**Pull request by jrwieland**
Major Changes:
Modified Playlist.lua file (adding song length).
Song Length automatically added to SF60 (updated as song is changed).
Added play next song automatically thru SF60 and code modifications.
Added pause song to LS61.
Added a line for user input to assign a reset Timer3 to Random Song switch
the user input will assigned SF31 (Necessary since the switch can be held awhile)
Added BGMusic|| to SF32.
Rewrote instructions in iTunes.lua to reflect current version.
Updated Screenshots.
Updated README (screenshots and instructions for installation and usage)
I'm not sure the French changes came out perfectly (I used google translate)

Minor Changes
cleaned code (reduced spacing used for some commands)
removed comments (used for code referencing)

### CODE REVIEW

**Comment by jrwieland** [comment]
ALL: 
I'm almost completed with the "Change playlist" functions
This will allow you to change your playlist depending on what you want to hear
  1.  perhaps something for a set sequence
  2. Another for relaxing between flights
  3. Yet another for general flying
  4. and yet another for .........
I need to write up the Readme instructions and check it on the Q7 before sending a pull request.

I have completed the Auto-create for playlists.
This makes it easy to create new playlists, not only when you want to change it all up, but also imports extracts the song length, in seconds, an places it in the playlist.
Both of these should be completed by the end of the weekend.

**Comment by jrwieland** [comment]
Version 2.1 Completed    
-----------
<b>Major Changes:</b>

Changed file structure
Added options to choose 4  playlists from the main screen.
Changed location of playlist.lua files
Modified playlist.lua file syntax (adding song length).     

Renamed files    
iTunes became main.lua (the actual "program") 
The Current iTunes.lua is a wrapper that changes the playlists and calls the program.

Added instructions for automatic playlist creation    

Rewrote instructions in main.lua to reflect current version.
Song Length automatically added to SF60 (updated as song is changed).
Added a line for user input to assign a reset Timer3 to Random Song switch
the user input will assigned SF31 (Necessary since the switch can be held awhile)
Added BGMusic|| to SF32.
Updated README (screenshots and instructions for installation and usage)
I'm not sure the French changes came out perfectly (I used google translate)

<b>Minor Changes</b>
Updated Screenshots.

**Comment by GilDev** [comment]
Hey John!

Finally took the time to look at your work. First, thanks a lot for taking the time to improve TaraniTunes, I’m glad people find this script useful!

I like what you have added (playlists, song length…), those were all features I actually planned to implement but I didn’t ended up doing it because I wanted TaraniTunes to stay simple, because I think it’s already hard enough to set up in its current state. Now you have two `.lua` files, 5 folders to create, 4 `playlist.txt` files to generate, Timer3 to set up… Thus, I don’t think it would be great to merge everything in the master branch, but maybe we can make a “dev” branch where everything can be merged, or maybe you would prefer that I put a link at the top of the current README to link to your repo?

Please tell me what you think about all this. I will now push some commits to your fork, because I have spotted some typos and French mistakes. =)

**Comment by jrwieland** [comment]
Gil: 
I would be happy to host the advanced version of the program for those who are interested.  

If you make a DEV branch, I feel that people would be less inclined to check it out, thinking it was a beta version of what's to come rather than something that is usable now. just my 2 cents, I am good ether way.  It is your program after all, I just added some additional functions I felt it needed.

I look forward to the corrections in french.

Thank you again.

**Comment by GilDev** [comment]
I was suggesting the “Dev” name but it could be named “Enhanced” or “Playlist version” for that matter. =) But I understand your point, and I will add a link on my repo’s Readme so people can find your enhanced version more easily.
I’ve updated the Readme on your repo with all the little mistakes I have spotted.

**Comment by GilDev** [comment]
There you go! 71a740a
Thanks a lot once more for your work! I hope TaraniTunes will continue to be useful to you and others!

**Pull request closed without merging**
